# Custom Language File for Launcher Customizer

[ejs.app]
title = "DGFE Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Velkommen Til DGFE Launcher"
welcomeDescription = ""
welcomeDescCTA = "Klik for at fors√¶tte."
